GET  http://127.0.0.1:8000/progress
Content-Type: application/json

{
    "URL" : "https://xyxsiuaxedneofkbjsej.supabase.co/storage/v1/object/public/test/video%20(720p).mp4",
    "title" : "title",
    "overlay" : "dinvite.png"
}

###
GET https://moviepy-1-a7680367.deta.app/
server{
    listen 80;
    server_name http://143.42.69.43 example.com;

    location / {
        proxy_pass http://localhost:8000;
    }
}